[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Serverless Functions for API routes
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer"]

# Next.js specific configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
